version: "3"
services:
  portal:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: cormorack/data-team-portal:latest
    ports:
      - 80:80
    volumes:
      - ./docker.php:/var/www/html/config/app.php:consistent
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - ooinetwork
  db-loader:
    build:
      context: ../
      dockerfile: ./docker/backend.dockerfile
    image: cormorack/data-team-portal-loader:latest
    volumes:
      - ./backend-config.cfg:/opt/datateam/datateam-portal-backend/config.cfg:consistent
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - ooinetwork
  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: visualocean
    networks:
      - ooinetwork
      
networks:
  ooinetwork: